name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Conan cache environment variables
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"
  CLANG_TIDY_VERSION: "13.0.0"

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-20.04
        compiler:
          - gcc-11
        build_type:
          - Debug
          - Release

        include:
          - compiler: gcc-11
            gcov_executable: gcov

          - os: ubuntu-20.04
            compiler: gcc-11
            generator: "Unix Makefiles"
            build_type: Debug
            gcov_executable: gcov

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Setup Cache
      #   uses: actions/setup_cache
      #   with:
      #     compiler: ${{ matrix.compiler }}
      #     build_type: ${{ matrix.build_type }}
      #     generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}

          cmake: true
          ninja: true
          ccache: true
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}
          cppcheck: true
          gcovr: true
          opencppcoverage: true

      - name: Configure CMake
        run: cmake -B ./build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DOPT_ENABLE_COVERAGE=${{ matrix.build_type == 'Debug' }}

      - name: Build
        run: cmake --build ./build/test --config ${{matrix.build_type}}

      - name: Unix - Test and coverage
        working-directory: ./build/test
        run: |
          ctest -C ${{matrix.build_type}}
          gcovr -j ${{env.nproc}} --delete --root ../../ --print-summary --xml-pretty --xml coverage.xml . --gcov-executable '${{ matrix.gcov_executable }}'

      # - name: Publish to codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     flags: ${{ runner.os }}
      #     name: ${{ runner.os }}-coverage
      #     files: ./build/coverage.xml