name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-20.04
          - macos-11
          - windows-2022
        compiler:
          - gcc-11
          - llvm-13.0.0
        build_type:
          - Debug
          - Release

        include:
          - os: windows-2022
            compiler: msvc
            build_type: Debug

          - os: windows-2022
            compiler: msvc
            build_type: Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true

      - name: Configure CMake
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ./build --target injector-tests --config ${{matrix.build_type}} -j 4

      - name: Run Tests
        working-directory: ./build
        run: ctest -C ${{matrix.build_type}}
          

      # - name: Publish to codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     flags: ${{ runner.os }}
      #     name: ${{ runner.os }}-coverage
      #     files: ./build/coverage.xml

  Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-11
          cmake: true
          gcovr: true

      - name: Configure CMake
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build ./build --target injector-tests --config Debug -j 4

      - name: Test and Coverage
        working-directory: ./build
        run: |
          ctest -C Debug
          gcovr --delete --root ../ --print-summary --xml-pretty --xml coverage.xml . --gcov-executable gcov